### ISSUE TITLE
功能建议：在多列显示时，书签可以按横向顺序进行排列，目前是竖向排列，第一列排完再排第二列

### ISSUE THREAD

**Issue by pswxy1314** [qinxs/Ease-Bookmarks#50]
如题，感谢

**Comment by qinxs** [comment]
我这边试了下 现在的布局设计不能很好地支持先横向排

以下是先横向排的自定义css：
```css
#search-list, .folder-list {
    grid-auto-flow: row;
}
```

因为扩展在布局这块设计有点复杂了
支持控制（最大）布局列数、每列条数、还有上下左右等快捷键
而上面的css 会导致这些全部失效 而且通过程序 也不能修复

如果以后简化布局设计 会考虑你说的情况
